#!/bin/bash
file=$1

function static() {
	shopt -s nullglob
	while true; do
		cd $file
		echo ""
		echo "all files in $file :"
		ls
		files=()
		for i in *.jpg *.png; do
			[[ -f $i ]] && files+=("$i")
		done
		range=${#files[@]}
		((range)) && feh --bg-scale "${files[RANDOM % range]}"
		sleep 1800s
	done
}

function dynamic() {
	xwinwrap -ov  -ni -fs -- mpv -vo x11 -wid WID --keepaspect=no --loop $file
}

function show_help() {
	cat <<-EOF 
DSACW : 
		Dotfiles Scripts auto change wallpapers!                               
Usage :
		DSACW \$1 		
		if "\$1" is dir then change static wallpapers, 
		if "\$1" is file then use this wallpaper(which mpv supported), 
		if "\$1" doesn't exist then cycle static wallpaper in the "~/.dotfiles/Pics/wallpapers "
	EOF
}


if [ x"$1" = x ]; then 
	file=~/.dotfiles/Pics/wallpapers
	show_help
	static & # > /dev/null
elif [ -f $1 ];then
	echo "$1 is file"
	dynamic
elif [ -d $1 ];then
	echo "$1 is dir"
	static
else
	notify-send "Wallpapers switch wrong"
fi
